name: Build and Release Organizador Set DJ

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        # Instalar dependências do sistema para librosa
        choco install ffmpeg
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Install additional dependencies for build
      run: |
        # Dependências extras para build robusto
        pip install lazy-loader
        pip install msgpack
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --clean OrganizadorSetDJ_GitHub.spec
        
    - name: Test executable
      run: |
        # Testar se o executável foi criado
        if (Test-Path "dist/OrganizadorSetDJ.exe") {
          Write-Host "Executável criado com sucesso!"
          Get-ChildItem dist/OrganizadorSetDJ.exe | Format-List Name, Length, LastWriteTime
        } else {
          Write-Error "Falha ao criar o executável!"
          exit 1
        }
        
    - name: Prepare release artifacts
      run: |
        # Criar pasta de distribuição
        New-Item -ItemType Directory -Force -Path "release"
        
        # Copiar executável
        Copy-Item "dist/OrganizadorSetDJ.exe" "release/"
        
        # Copiar documentação
        Copy-Item "README.md" "release/"
        Copy-Item "COMO_GERAR_EXE.md" "release/"
        
        # Criar arquivo de versão
        $version = if ($env:GITHUB_REF -match "refs/tags/(.+)") { $matches[1] } else { "dev-build" }
        "Versão: $version`nData de Build: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" | Out-File -FilePath "release/VERSION.txt" -Encoding UTF8
        
    - name: Create ZIP archive
      run: |
        Compress-Archive -Path "release/*" -DestinationPath "OrganizadorSetDJ-Windows.zip"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OrganizadorSetDJ-Windows
        path: |
          release/
          OrganizadorSetDJ-Windows.zip
          
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          OrganizadorSetDJ-Windows.zip
          release/OrganizadorSetDJ.exe
        body: |
          ## Organizador Set DJ - ${{ github.ref_name }}
          
          ### Download
          - **OrganizadorSetDJ.exe**: Executável principal para Windows
          - **OrganizadorSetDJ-Windows.zip**: Pacote completo com documentação
          
          ### Funcionalidades
          - Interface gráfica intuitiva para organização de sets de DJ
          - Análise automática de BPM, nota musical e volume
          - Sistema de sugestões harmônicas baseado no Camelot Wheel
          - Player integrado com barra de progresso interativa
          - Drag & drop para organização de músicas
          - Exportação de sets em formato de texto
          
          ### Como usar
          1. Baixe o arquivo `OrganizadorSetDJ.exe`
          2. Execute o arquivo (não precisa instalar)
          3. Selecione uma pasta com suas músicas
          4. Organize seu set arrastando as músicas
          
          ### Requisitos do Sistema
          - Windows 10 ou superior
          - Arquivos de áudio nos formatos: MP3, WAV, FLAC, OGG
          
          Build gerado automaticamente via GitHub Actions
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
